### PR TITLE
Test files nested array feature

### PR DESCRIPTION
**Pull request by xNok**
this PR provides and example with nested array where an article as many authors and you ant to reverse it by grouping articles by authors.

This is the code I used to generate the solution

```js
// create a temporary array `authors`
  result.forEach(function(item) {
      item.authors = item.author.map(function(x) {
         return x.family;
      })
  });

// groupby authors
  finalresult = groupBy(result, ['authors']);

// delete the temporary array
  Object.keys(finalresult).forEach(function (key){
    finalresult[key].forEach(function (item){
      delete item.authors
    });
  });
```

### CODE REVIEW

**Comment by gagan-bansal** [comment]
Thanks for detailed input.

**Comment by gagan-bansal** [comment]
I was setting different test cases for recursive properties grouping. If we give option for recursive then cases are very complex to implement. Like here is one example of vendors who have stores in different cities and localities. Shown here one vendor:
```json
{
  "id": 1,
  "addresses": [
    {
      "city": "a",
      "localities": [
        {
          "name": "x",
          "zipcode": "12345"
        },
        {
          "name": "y",
          "zipcode": "12346"
        }
      ]
    },
    {
      "city": "b",
      "localities": [
        {
          "name": "x",
          "zipcode": "12345"
        },
        {
          "name": "z",
          "zipcode": "12347"
        }
      ]
    }
  ],
  "detail": {
    "name": "foo",
    "items": 400
  }
}

```  

Your use case was upto `addresses.city` but user would like to group by `addresses.localities.zipcode` also. There can be further more complex possibilities.

I recommend not to implement the recursive feature in this module as the complexity of code would be very high and it would be difficult to cover all test cases.

For your use case the way you have implement using this module as external seems best. So in case of recursive data user has to simplify (remove recursion)  the data and use this module.

Looking your point of view.

**Comment by xNok** [comment]
> For your use case the way you have implement using this module as external seems best. So in case of recursive data user has to simplify (remove recursion) the data and use this module.

Remove the recursion could be tedious and a lot of code to write. In my mind manipulating data and grouping the them by a property should as easy as `groupBy(result, ['addresses.localities.zipcode']);` no matter how nested your data are. This is to me the main goal in developing such npm packages.

> Your use case was up to addresses.city but user would like to group by addresses.localities.zipcode also. There can be further more complex possibilities.

The problem their is to create a recursive function that do the job. Their is not that much different use case if you consider that JSON contain only few types (Object, Array, String). So if you decompose addresses.localities.zipcode. it is Array.Array.String. It won`t be more difficult to resolve Array.Array.Array.String given that you are using a recursive function.

This is the one I built to "flatten" the nested array

```javascript
/**
* return the value associated to an array of recurcive keys
* ["first","second", .. ,"last"] find the list "last" properties
* according to the previous ones
*/
function getKey(data, group) {
 key = group.shift();

 //If array reduce to flatten
 if (Array.isArray(data)){
    data = data.reduce(function(a, b) {
      return a.concat(b[key]);
    }, []);
    // Flat array
    if (group.length == 0) return data;
    // Nested array
    return getKey(data, group);
 }

  //If no more properties to explore
  if (group.length == 0) return data[key];

  //If we need to explore deeper
  return getKey(data[key], group);
}
```

I managed to solve those use case given as set of data similar to the one you showed me. 

```javascript
//groupBy addresses.city

root  = "addresses"
group = ["city"]

result = reverse_relation(data, root, group)
jsonfile.writeFile('./tmp/nested1.json', result, {spaces: 2}, (err) => {});

//groupBy addresses.localities.zipcode

root  = "addresses"
group = ["localities","zipcode"]

result = reverse_relation(data, root, group)
jsonfile.writeFile('./tmp/nested2.json', result, {spaces: 2}, (err) => {});
```

Given the reverse_relation function

```javascript
/*
* Resolve the groupby for nested array
*/
function reverse_relation(data,root,group){

  // create a temporary array
  data.forEach(function(item) {
      groupClone = group.slice();
      item["tmp"] = getKey(item[root], groupClone, 0)
  });

  // groupby temporary categories
  finalresult = groupBy(data, ['tmp']);

  // delete the temporary array
  Object.keys(finalresult).forEach(function (key){
    finalresult[key].forEach(function (item){
      delete item.tmp
    });
  });

  return finalresult
}
```

**Comment by gagan-bansal** [comment]
Seems very promising, I liked your eagerness and actionable approach. You didn't give up. Certainly I'll implement this on coming weekend. I would be happy to see you as contributer if you are willing to take up this issue and write code. If willing please let me know we can first write the test case.

**Comment by xNok** [comment]
I would be happy to help, but yet i didn't look into detail how you did to collect the data and groupby multiple properties. 

We should list the test case we wanna test such as:

* [ ] groupBy(data, [array.string])  - 1 property 1 lvl array
* [ ] groupBy(data, [array.array.string])  - 1 property 2 lvl array
* [ ] groupBy(data, [array.string2, string1])) - 2 properties 1 lvl array

Then create json files as use case. I don't know yet the fastest way to input and output for those use cases.

**Comment by gagan-bansal** [comment]
Yes such test cases are fine. I'll look into details for test cases and will write the same soon.

**Comment by gagan-bansal** [comment]
I was busy in some urgent work, this week I'll implement it.

**Comment by xNok** [comment]
I have work on the problem, you can see what i did on https://github.com/xNok/json-groupby/blob/feature-nesteArray/json-groupby.js

the `groupByCategory` take as parameters the list of item and a function. The function in the second parameter must return which category/categories an item belongs to.

```
groupByCategory(items, iteratee)
```

Basically i took inspiration from underscore.js synthax.

```
_.groupBy([1.3, 2.1, 2.4], function(num){ return Math.floor(num); });
=> {1: [1.3], 2: [2.1, 2.4]}
```

By doing so you have a generic way to group by something such a the floor, or the square or any rule that you want.

As a result to get the same coverage as your repository you need to use the `valueAt` function as the iteratee
```
group = groupByCategory(items, function(item) {
   return valueAt(item, properties[0]);
});
```

To resolve nested array we need to create a modified version of the `getKey` function I proposed In the previous message

```
group = groupByCategory(items, function(item) {
   return getKey(item, properties[0]);
});
```

This `getKey` function is like a other version of `valueAt` that can resolve nested arrays. The fact is that you found a very efficient `valueAt` function on stackoverflow, So there is probably a version that resolve nested arrays.

**Comment by gagan-bansal** [comment]
I am reworking on `valueAt` function for nested array, that we discussed earlier to solve property path like `array.object.array.object.string`. Almost done for the use cases we discussed earlier, I'll commit the dev branch in one or two days.

Idea of passing function as iteratee is alos very nice that we can take in second phase.

**Comment by gagan-bansal** [comment]
@xNok I have pushed branch "feature-nestedArray" with nested array support. I have changed `valueAt` function to support property path in nested arrays too.

There are last 3 test cases in `test/test.js`. You can please do some testing and if there is some issue please let me know.
I'll update README.md once our testing is completed.

**Comment by gagan-bansal** [comment]
@xNok  Hope the "feature-nestedArray"  branch now solves your requirement, in case of any error please let me know.

**Comment by xNok** [comment]
Nice job. I haven't had the time to look at it yet. I will test it soon and gives you my feedback.

**Comment by xNok** [comment]
I went through and did some test, every thing seems to work fine. The new  `valueAt` does perfectly its job and even fulfill its own use case like retrieving all the possible zip-codes `propertyAt(data, "address.zipcode")`.

If you need extra test case or some documentation let me know(I see a typo on the subtitle: `Group array of JOSN objects based on associated properties.` it should be `JSON`) 

thanks for taking care of this feature

**Comment by gagan-bansal** [comment]
@xNok thank you very much for your support and time. I'll correct the typo. Your contribution for motivation and technical discussion is highly regarded.

**Comment by gagan-bansal** [comment]
This feature is added in this [commit](https://github.com/gagan-bansal/json-groupby/commit/6cb69a0)

**Pull request closed without merging**
